<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
return array(		    
			array(
				'name'=>'燕郊镇',
				'parent'=>array('name'=>'廊坊市'),
			),
			array(
				'name'=>'涿州市',
				'parent'=>array('name'=>'保定市'),
			),
			array(
				'name'=>'三河市',
				'parent'=>array('name'=>'廊坊市'),
				),
			array(
				'name'=>'固安县',
				'parent'=>array('name'=>'廊坊市'),
			),
			array(
				'name'=>'香河县',
				'parent'=>array('name'=>'廊坊市'),
			),
			array(
				'name'=>'涞水县',
				'parent'=>array('name'=>'保定市'),
			),
			array(
				'name'=>'涿鹿县',
				'parent'=>array('name'=>'张家口市'),
			),
			array(
				'name'=>'怀来县',
				'parent'=>array('name'=>'张家口市'),
			),
			array(
				'name'=>'赤城县',
				'parent'=>array('name'=>'张家口市'),
			),
			array(
				'name'=>'滦平县',
				'parent'=>array('name'=>'承德市'),
			),
			array(
				'name'=>'广阳区',
				'parent'=>array('name'=>'廊坊市'),
			),
			array(
				'name'=>'安次区',
				'parent'=>array('name'=>'廊坊市'),
			),
			array(
				'name'=>'丰宁满族自治县',
				'parent'=>array('name'=>'承德市'),
			),
			array(
				'name'=>'大厂回族自治县',
				'parent'=>array('name'=>'廊坊市'),
			)					
	);